// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useState, useEffect, useMemo, useRef } from "react";
import {
  ExternalLink,
  Mail,
  Instagram,
  TrendingUp,
  Utensils,
  FileText,
  Rocket,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Maximize2,
  X,
  File,
  FolderOpen,
  Image,
  Database,
  Wrench,
  Sparkles,
  Activity,
  BookOpen,
  Sticky,
  StickyNote,
  Folder,
} from "lucide-react";

const passions = [
  {
    emoji: "🎨",
    title: "Design",
    description: "Streetwear, concept building, branding, and visual storytelling",
    links: [{ name: "View Design Gallery", url: "/design" }],
  },
  { emoji: "🎧", title: "Music", description: "Writing, recording, crafting flows, and pushing creative boundaries", links: [] },
  {
    emoji: "🔐",
    title: "Cybersecurity",
    description: "Always learning, always curious. Exploring systems and security",
    links: [
      { name: "Open Cybersecurity Briefing", url: "/cyber" },
      { name: "Live Threats", url: "/threats" },
      { name: "CISA KEV Catalog", url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog" },
    ],
  },
  { emoji: "🤖", title: "AI", description: "Prompts, workflows, and practical ways to make life easier", links: [] },
  {
    emoji: "💼",
    title: "Investor",
    description: "Backed several spirits companies plus a few tech startups",
    links: [
      { name: "Oneroq Club", url: "https://oneroqclub.com" },
      { name: "Clearwater Distilling", url: "https://clearwaterdistilling.com" },
      { name: "Fanbase", url: "https://fanbase.app" },
      { name: "Legion M", url: "https://legionm.com" },
      { name: "A7FL", url: "https://www.a7fl.com" },
      { name: "Metaknyts", url: "https://metaknyts.com" },
      { name: "Cheers Health", url: "https://cheershealth.com" },
      { name: "Boone's Bourbon", url: "https://www.drinkboonesbourbon.com" },
    ],
    footer: "And a host of others...",
  },
  {
    emoji: "🍜",
    title: "Foodie",
    description: "Good food? I'm there. Always hunting for the next best bite",
    links: [{ name: "View Food Gallery", url: "/foodie" }],
  },
];

const projects = [
  { title: "🎓 Zo Teacher OS", description: "Lesson planning automation for K-12. Prompt builder + multi-format exports", icon: BookOpen, link: "/teacher-os" },
  { title: "📝 Stickie ZO", description: "Personal note capture system with a beautiful web interface", icon: StickyNote, link: "https://stickiezo-dagawdnyc.zocomputer.io" },
  { title: "Zo Reporting Command Center", description: "Broadcast-style Zo news and social monitoring dashboard", icon: Activity, link: "/zo-desk" },
  { title: "ZO Control Deck", description: "Private multi-tab control dashboard for services, agents, credits, routes, logs, and system status", icon: Wrench, link: "/dashboard" },
  { title: "Open Security Briefing", description: "Open cyber and threat intelligence briefing dashboard", icon: FileText, link: "/cyber" },
  { title: "Zo Computer Research Report", description: "Deep dive into the intelligent cloud computer revolution", icon: FileText, link: "/research" },
  { title: "Stocks Dashboard", description: "Real-time stock tracking and portfolio management tool", icon: TrendingUp, link: "/stocks" },
  { title: "Bitcoin Dashboard", description: "Live Bitcoin price tracking and market analytics", icon: TrendingUp, link: "https://project-russel-site-dagawdnyc.zocomputer.io" },
  { title: "My Food Matrix", description: "Interactive map of my favorite food spots and reviews", icon: Utensils, link: "/eats" },
  { title: "Astranode-v2", description: "AI-powered automation and workflow platform", icon: Rocket, link: "https://astranode-v2-dagawdnyc.zocomputer.io" },
  { title: "Signal Pulse", description: "Turn meeting notes into action items, risks, and an execution score", icon: Activity, link: "/signal-pulse" },
];

const DESIGN_PHOTOS = [
  "/design-photos/design-01.jpg",
  "/design-photos/design-02.jpg",
  "/design-photos/design-03.jpg",
  "/design-photos/design-04.jpg",
  "/design-photos/design-05.jpg",
  "/design-photos/design-06.png",
  "/design-photos/design-07.png",
  "/design-photos/design-08.jpg",
  "/design-photos/design-09.jpg",
  "/design-photos/design-10.jpg",
  "/design-photos/design-11.jpg",
  "/design-photos/design-12.jpg",
  "/design-photos/design-13.jpg",
  "/design-photos/design-14.jpg",
  "/design-photos/design-15.jpg",
  "/design-photos/design-16.jpg",
  "/design-photos/design-17.jpg",
  "/design-photos/design-18.png",
  "/design-photos/design-19.jpg",
  "/design-photos/design-20.png",
  "/design-photos/design-21.png",
  "/design-photos/design-22.jpg",
  "/design-photos/design-23.jpg",
  "/design-photos/design-24.jpg",
  "/design-photos/design-25.jpg",
  "/design-photos/design-26.jpg",
  "/design-photos/design-27.jpg",
  "/design-photos/design-28.jpg",
  "/design-photos/design-29.jpg",
  "/design-photos/design-30.jpg",
  "/design-photos/design-31.jpg",
  "/design-photos/design-32.jpg",
  "/design-photos/design-33.jpg",
  "/design-photos/design-34.jpg",
  "/design-photos/design-35.jpg",
  "/design-photos/design-36.jpg",
  "/design-photos/design-37.jpg",
  "/design-photos/design-38.jpg",
  "/design-photos/design-39.jpg",
  "/design-photos/design-40.jpg",
  "/design-photos/design-41.jpg",
  "/design-photos/design-42.jpg",
  "/design-photos/design-43.jpg",
  "/design-photos/design-44.jpg",
  "/design-photos/design-45.jpg",
];

function wrapIndex(i: number, len: number) {
  if (len <= 0) return 0;
  return ((i % len) + len) % len;
}

function DesignCarousel({ photos, onOpen }: { photos: string[]; onOpen?: (idx: number) => void }) {
  const [idx, setIdx] = useState(0);
  const [dir, setDir] = useState<1 | -1>(1);

  const current = photos[idx] || "";

  const go = (next: number, nextDir: 1 | -1) => {
    if (!photos.length) return;
    setDir(nextDir);
    setIdx(wrapIndex(next, photos.length));
  };

  const prev = () => go(idx - 1, -1);
  const next = () => go(idx + 1, 1);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowLeft") prev();
      if (e.key === "ArrowRight") next();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [idx, photos.length]);

  return (
    <div className="mt-3">
      <div className="relative rounded-xl overflow-hidden border border-cyan-400/15 bg-zinc-950/40">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute inset-0 opacity-[0.22]" style={{ background: "radial-gradient(900px 300px at 50% 0%, rgba(34, 211, 238, 0.18), transparent 60%)" }} />
          <div className="absolute inset-0 opacity-[0.14]" style={{ background: "linear-gradient(90deg, rgba(34,211,238,0.0), rgba(167,139,250,0.12), rgba(34,211,238,0.0))" }} />
          <div className="absolute inset-0 scanlines" />
        </div>

        <div className="aspect-[16/9] w-full relative">
          <button
            type="button"
            className="lb-open"
            onClick={(e) => {
              e.stopPropagation();
              onOpen?.(idx);
            }}
            aria-label="Open design photos"
            title="Open"
          >
            <Maximize2 className="w-4 h-4" />
          </button>

          <img
            key={current}
            src={current}
            alt={`Design ${idx + 1}`}
            className={"absolute inset-0 w-full h-full object-contain p-2 select-none cursor-zoom-in " + (dir === 1 ? "slide-in-right" : "slide-in-left")}
            loading="lazy"
            draggable={false}
            onClick={(e) => {
              e.stopPropagation();
              onOpen?.(idx);
            }}
          />

          <button
            className="nav-btn left-3"
            onClick={(e) => {
              e.stopPropagation();
              prev();
            }}
            aria-label="Previous design photo"
          >
            <ChevronLeft className="w-5 h-5" />
          </button>
          <button
            className="nav-btn right-3"
            onClick={(e) => {
              e.stopPropagation();
              next();
            }}
            aria-label="Next design photo"
          >
            <ChevronRight className="w-5 h-5" />
          </button>

          <div className="absolute bottom-3 left-3 flex items-center gap-2 rounded-full px-3 py-1.5 hud">
            <span className="dot" />
            <span className="text-xs text-zinc-200 tracking-wide">Design Photos</span>
            <span className="text-zinc-500 text-xs">{idx + 1} / {photos.length}</span>
          </div>
        </div>
      </div>

      <div className="mt-2 text-[11px] text-zinc-500">Tip: click the image to open, or use your keyboard arrows ← →</div>
    </div>
  );
}

function DesignLightbox({
  photos,
  index,
  onClose,
}: {
  photos: string[];
  index: number | null;
  onClose: () => void;
}) {
  const [idx, setIdx] = useState(0);

  useEffect(() => {
    if (index === null) return;
    setIdx(wrapIndex(index, photos.length));
  }, [index, photos.length]);

  useEffect(() => {
    if (index === null) return;

    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
      if (e.key === "ArrowLeft") setIdx((v) => wrapIndex(v - 1, photos.length));
      if (e.key === "ArrowRight") setIdx((v) => wrapIndex(v + 1, photos.length));
    };
    window.addEventListener("keydown", onKey);

    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = prevOverflow;
    };
  }, [index, onClose, photos.length]);

  if (index === null) return null;

  const current = photos[idx] || "";

  return (
    <div
      className="lb-backdrop"
      role="dialog"
      aria-modal="true"
      aria-label="Design photos"
      onClick={onClose}
    >
      <div className="lb-panel" onClick={(e) => e.stopPropagation()}>
        <button className="lb-close" onClick={onClose} aria-label="Close">
          <X className="w-5 h-5" />
        </button>

        <button
          className="lb-nav lb-left"
          onClick={() => setIdx((v) => wrapIndex(v - 1, photos.length))}
          aria-label="Previous"
        >
          <ChevronLeft className="w-6 h-6" />
        </button>
        <button
          className="lb-nav lb-right"
          onClick={() => setIdx((v) => wrapIndex(v + 1, photos.length))}
          aria-label="Next"
        >
          <ChevronRight className="w-6 h-6" />
        </button>

        <div className="lb-stage">
          <img src={current} alt={`Design ${idx + 1}`} className="lb-img" draggable={false} />
        </div>

        <div className="lb-footer">
          <div className="flex items-center gap-2">
            <span className="dot" />
            <span className="text-xs text-zinc-200 tracking-wide">Design Photos</span>
            <span className="text-zinc-500 text-xs">{idx + 1} / {photos.length}</span>
          </div>
          <div className="text-[11px] text-zinc-500">Esc to close, arrows to navigate</div>
        </div>
      </div>
    </div>
  );
}

const iconMap: Record<string, any> = {
  FileText,
  Sparkles,
  Wrench,
  Image,
  Database,
  FolderOpen,
};

type Star = {
  x: number;
  y: number;
  z: number;
  px: number;
  py: number;
  hue: number;
  tw: number;
};

function clamp(n: number, a: number, b: number) {
  return Math.max(a, Math.min(b, n));
}

function WarpSpeedBackground({ intensity = 0.62, density = 0.58, trail = 0.74 }: { intensity?: number; density?: number; trail?: number }) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const hostRef = useRef<HTMLDivElement | null>(null);
  const rafRef = useRef<number>(0);
  const starsRef = useRef<Star[]>([]);
  const sizeRef = useRef({ w: 1, h: 1, dpr: 1 });
  const reducedRef = useRef(false);
  const visibleRef = useRef(true);

  const params = useMemo(() => {
    const base = {
      zMax: 1800,
      fov: 360,
      baseSpeed: 10,
      warpSpeed: 58,
      bgFade: 0.16,
    };

    return {
      ...base,
      speed: base.baseSpeed + (base.warpSpeed - base.baseSpeed) * intensity,
      count: Math.floor(360 + density * 1050),
      trail: 0.55 + trail * 2.4,
      fade: base.bgFade - intensity * 0.06,
    };
  }, [density, intensity, trail]);

  useEffect(() => {
    reducedRef.current = window.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches ?? false;
    const onVis = () => {
      visibleRef.current = document.visibilityState === "visible";
    };
    document.addEventListener("visibilitychange", onVis);
    onVis();
    return () => document.removeEventListener("visibilitychange", onVis);
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    const host = hostRef.current;
    if (!canvas || !host) return;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const resetStar = (s: Star, w: number, h: number, zMax: number) => {
      const spread = Math.max(w, h) * 1.25;
      s.x = (Math.random() * 2 - 1) * spread;
      s.y = (Math.random() * 2 - 1) * spread;
      s.z = Math.random() * zMax + 40;
      s.px = 0;
      s.py = 0;
      s.hue = 190 + Math.random() * 70;
      s.tw = 0.35 + Math.random() * 0.65;
    };

    const ensureStars = (count: number) => {
      const { w, h } = sizeRef.current;
      const zMax = params.zMax;
      const arr = starsRef.current;
      while (arr.length < count) {
        const s: Star = { x: 0, y: 0, z: 0, px: 0, py: 0, hue: 210, tw: 0.6 };
        resetStar(s, w, h, zMax);
        arr.push(s);
      }
      while (arr.length > count) arr.pop();
    };

    const resize = () => {
      const rect = host.getBoundingClientRect();
      const w = Math.max(1, Math.floor(rect.width));
      const h = Math.max(1, Math.floor(rect.height));
      const dpr = Math.max(1, Math.min(2, window.devicePixelRatio || 1));
      sizeRef.current = { w, h, dpr };
      canvas.width = Math.floor(w * dpr);
      canvas.height = Math.floor(h * dpr);
      canvas.style.width = w + "px";
      canvas.style.height = h + "px";
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

      for (const s of starsRef.current) resetStar(s, w, h, params.zMax);
    };

    resize();
    ensureStars(params.count);

    const ro = new ResizeObserver(() => resize());
    ro.observe(host);

    let last = performance.now();
    let speedNow = params.speed;

    const tick = (t: number) => {
      rafRef.current = requestAnimationFrame(tick);
      if (!visibleRef.current) return;

      const dt = Math.min(0.04, (t - last) / 1000);
      last = t;

      ensureStars(params.count);

      if (reducedRef.current) {
        ctx.clearRect(0, 0, sizeRef.current.w, sizeRef.current.h);
        return;
      }

      const { w, h } = sizeRef.current;
      const cx = w * 0.5;
      const cy = h * 0.5;

      speedNow += (params.speed - speedNow) * 0.05;

      ctx.globalCompositeOperation = "source-over";
      ctx.fillStyle = `rgba(2, 6, 23, ${clamp(params.fade, 0.06, 0.22)})`;
      ctx.fillRect(0, 0, w, h);

      ctx.globalCompositeOperation = "lighter";

      const fov = params.fov;
      const trailK = params.trail;

      for (let i = 0; i < starsRef.current.length; i++) {
        const s = starsRef.current[i];
        const zPrev = s.z;

        s.z -= speedNow * (dt * 60);
        if (s.z < 1) {
          resetStar(s, w, h, params.zMax);
          continue;
        }

        const k = fov / (fov + s.z);
        const x = cx + s.x * k;
        const y = cy + s.y * k;

        const kp = fov / (fov + zPrev);
        const xp = cx + s.x * kp;
        const yp = cy + s.y * kp;

        const dx = x - xp;
        const dy = y - yp;
        const len = Math.sqrt(dx * dx + dy * dy);

        const alpha = clamp((0.1 + len / 18) * (0.18 + intensity * 0.55) * s.tw, 0.02, 0.85);
        const width = clamp(0.5 + len / 36, 0.6, 2.2);

        ctx.strokeStyle = `hsla(${s.hue}, 95%, 72%, ${alpha})`;
        ctx.lineWidth = width;
        ctx.beginPath();
        ctx.moveTo(xp, yp);
        ctx.lineTo(xp + dx * trailK, yp + dy * trailK);
        ctx.stroke();

        if (len < 1.2) {
          ctx.fillStyle = `rgba(255,255,255,${alpha * 0.7})`;
          ctx.fillRect(x - 0.5, y - 0.5, 1, 1);
        }
      }

      ctx.globalCompositeOperation = "source-over";
    };

    rafRef.current = requestAnimationFrame(tick);

    return () => {
      ro.disconnect();
      cancelAnimationFrame(rafRef.current);
    };
  }, [params, intensity]);

  return (
    <div ref={hostRef} className="absolute inset-0 pointer-events-none">
      <canvas ref={canvasRef} className="absolute inset-0 warp-canvas" />
    </div>
  );
}

export default function Home() {
  const [expandedCategory, setExpandedCategory] = useState<string | null>(null);
  const [expandedPassion, setExpandedPassion] = useState<string | null>(null);
  const [designLightbox, setDesignLightbox] = useState<number | null>(null);
  
  // File browser state
  const [groupBy, setGroupBy] = useState<"default" | "recent" | "types" | "projects">("default");
  const [fileCategories, setFileCategories] = useState<Array<{ name: string; files?: Array<{ name: string; path: string }> }>>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [savedKey, setSavedKey] = useState("");
  const [accessKey, setAccessKey] = useState("");

  useEffect(() => {
    const existing = (localStorage.getItem("my_files_api_token") || "").trim();
    setAccessKey(existing);
    setSavedKey(existing);
  }, []);

  const fetchFiles = async () => {
    if (!savedKey) {
      setError("Add an access key to view your files");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const groupParam = groupBy === "default" ? "" : `?group=${groupBy}`;
      const resp = await fetch(`/api/my-files${groupParam}`, {
        headers: {
          "x-api-key": savedKey,
          "Authorization": `Bearer ${savedKey}`,
          "Accept": "application/json",
        },
      });

      if (!resp.ok) {
        const data = (await resp.json()) as any;
        const base = typeof data?.error === "string" ? data.error : "Request failed";
        const reason = typeof data?.reason === "string" ? ` (${data.reason})` : "";
        setError(base + reason);
        setFileCategories([]);
        setLoading(false);
        return;
      }

      const data = (await resp.json()) as any;
      setFileCategories(data.categories || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
      setFileCategories([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (savedKey) {
      fetchFiles();
    }
  }, [groupBy, savedKey]);

  const saveKey = () => {
    const trimmed = accessKey.trim();
    if (trimmed) {
      localStorage.setItem("my_files_api_token", trimmed);
      setSavedKey(trimmed);
      setError(null);
    }
  };

  const clearKey = () => {
    localStorage.removeItem("my_files_api_token");
    setSavedKey("");
    setAccessKey("");
    setFileCategories([]);
  };

  return (
    <div className="min-h-screen text-white relative overflow-hidden">
      <div className="fixed inset-0 -z-10">
        <WarpSpeedBackground />

        <div className="absolute inset-0 bg-zinc-950/35" />

        <div
          className="absolute inset-0"
          style={{
            background:
              "radial-gradient(900px 600px at 50% 40%, rgba(34, 211, 238, 0.10), transparent 60%), radial-gradient(900px 600px at 50% 120%, rgba(99, 102, 241, 0.08), transparent 60%)",
            mixBlendMode: "screen",
          }}
        />

        <div
          className="absolute top-0 right-0 w-[500px] h-[500px] opacity-18 blur-[100px]"
          style={{ background: "linear-gradient(135deg, #ec4899, #8b5cf6)", animation: "gradient-shift 8s ease infinite" }}
        />
        <div
          className="absolute bottom-0 left-0 w-[400px] h-[400px] opacity-18 blur-[100px]"
          style={{
            background: "linear-gradient(135deg, #3b82f6, #06b6d4)",
            animation: "gradient-shift 10s ease infinite",
            animationDelay: "-3s",
          }}
        />
        <div
          className="absolute top-1/2 left-1/2 w-[300px] h-[300px] opacity-10 blur-[80px]"
          style={{
            background: "linear-gradient(135deg, #a855f7, #ec4899)",
            animation: "gradient-shift 12s ease infinite",
            animationDelay: "-6s",
          }}
        />

        <div
          className="absolute inset-0 opacity-[0.03]"
          style={{
            backgroundImage:
              "linear-gradient(rgba(255,255,255,.1) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.1) 1px, transparent 1px)",
            backgroundSize: "50px 50px",
          }}
        />

        <div
          className="absolute inset-0"
          style={{
            background:
              "radial-gradient(1200px 700px at 50% 30%, rgba(0,0,0,0.0), rgba(0,0,0,0.55) 70%, rgba(0,0,0,0.75) 100%)",
          }}
        />
      </div>

      <style>{`
        @keyframes gradient-shift {
          0%, 100% { opacity: 0.2; transform: translate(0, 0) scale(1); }
          50% { opacity: 0.3; transform: translate(20px, -20px) scale(1.1); }
        }
        @keyframes pegasus-float {
          0%, 100% { transform: translateY(0px) rotate(0deg); }
          50% { transform: translateY(-8px) rotate(1deg); }
        }
        @keyframes glow-pulse {
          0%, 100% { box-shadow: 0 0 30px rgba(236, 72, 153, 0.3), 0 0 60px rgba(139, 92, 246, 0.2); }
          50% { box-shadow: 0 0 50px rgba(236, 72, 153, 0.5), 0 0 100px rgba(139, 92, 246, 0.3); }
        }
        @keyframes sparkle {
          0%, 100% { opacity: 0; transform: scale(0); }
          50% { opacity: 1; transform: scale(1); }
        }

        .hud {
          border: 1px solid rgba(255,255,255,0.10);
          background: rgba(9, 9, 11, 0.45);
          backdrop-filter: blur(10px);
        }
        .dot {
          width: 6px;
          height: 6px;
          border-radius: 999px;
          background: rgba(34, 211, 238, 0.9);
          box-shadow: 0 0 12px rgba(34, 211, 238, 0.55);
        }
        .nav-btn {
          position: absolute;
          top: 50%;
          transform: translateY(-50%);
          display: inline-flex;
          align-items: center;
          justify-content: center;
          width: 42px;
          height: 42px;
          border-radius: 14px;
          border: 1px solid rgba(34, 211, 238, 0.25);
          background: rgba(2, 6, 23, 0.55);
          backdrop-filter: blur(10px);
          color: rgba(219, 234, 254, 0.92);
          box-shadow: 0 0 0 1px rgba(167, 139, 250, 0.10) inset, 0 0 26px rgba(34, 211, 238, 0.10);
          transition: transform 160ms ease, border-color 160ms ease, box-shadow 160ms ease;
        }
        .nav-btn:hover {
          border-color: rgba(34, 211, 238, 0.55);
          box-shadow: 0 0 0 1px rgba(167, 139, 250, 0.14) inset, 0 0 38px rgba(34, 211, 238, 0.16);
          transform: translateY(-50%) scale(1.04);
        }
        .nav-btn:active { transform: translateY(-50%) scale(0.98); }
        .nav-btn.left-3 { left: 12px; }
        .nav-btn.right-3 { right: 12px; }

        .lb-open {
          position: absolute;
          top: 10px;
          right: 10px;
          z-index: 20;
          display: inline-flex;
          align-items: center;
          justify-content: center;
          width: 36px;
          height: 36px;
          border-radius: 14px;
          border: 1px solid rgba(34, 211, 238, 0.22);
          background: rgba(2, 6, 23, 0.58);
          backdrop-filter: blur(10px);
          color: rgba(219, 234, 254, 0.9);
          box-shadow: 0 0 0 1px rgba(167, 139, 250, 0.10) inset, 0 0 24px rgba(34, 211, 238, 0.10);
        }
        .lb-open:hover { border-color: rgba(34, 211, 238, 0.55); }

        .lb-backdrop {
          position: fixed;
          inset: 0;
          z-index: 60;
          background: rgba(0,0,0,0.86);
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 20px;
        }
        .lb-panel {
          position: relative;
          width: min(1100px, calc(100vw - 40px));
          height: min(720px, calc(100vh - 40px));
          border-radius: 18px;
          overflow: hidden;
          border: 1px solid rgba(34, 211, 238, 0.22);
          background: rgba(2, 6, 23, 0.55);
          box-shadow: 0 0 0 1px rgba(167, 139, 250, 0.10) inset, 0 0 48px rgba(34, 211, 238, 0.10);
          backdrop-filter: blur(12px);
        }
        .lb-panel:before {
          content: "";
          position: absolute;
          inset: 0;
          background:
            radial-gradient(900px 300px at 50% 0%, rgba(34, 211, 238, 0.16), transparent 60%),
            linear-gradient(90deg, rgba(34,211,238,0.0), rgba(167,139,250,0.10), rgba(34,211,238,0.0));
          opacity: 0.9;
          pointer-events: none;
        }
        .lb-panel:after {
          content: "";
          position: absolute;
          inset: 0;
          background: repeating-linear-gradient(
            to bottom,
            rgba(255,255,255,0.03),
            rgba(255,255,255,0.03) 1px,
            rgba(255,255,255,0.0) 2px,
            rgba(255,255,255,0.0) 6px
          );
          mix-blend-mode: overlay;
          opacity: 0.8;
          pointer-events: none;
        }
        .lb-close {
          position: absolute;
          top: 14px;
          right: 14px;
          z-index: 30;
          width: 42px;
          height: 42px;
          border-radius: 16px;
          border: 1px solid rgba(255,255,255,0.12);
          background: rgba(9, 9, 11, 0.35);
          color: rgba(255,255,255,0.86);
          display: inline-flex;
          align-items: center;
          justify-content: center;
          backdrop-filter: blur(10px);
        }
        .lb-close:hover { border-color: rgba(34, 211, 238, 0.45); }

        .lb-nav {
          position: absolute;
          top: 50%;
          transform: translateY(-50%);
          z-index: 30;
          width: 54px;
          height: 54px;
          border-radius: 18px;
          border: 1px solid rgba(34, 211, 238, 0.28);
          background: rgba(2, 6, 23, 0.62);
          color: rgba(219, 234, 254, 0.94);
          box-shadow: 0 0 0 1px rgba(167, 139, 250, 0.12) inset, 0 0 32px rgba(34, 211, 238, 0.12);
          backdrop-filter: blur(12px);
        }
        .lb-nav:hover { border-color: rgba(34, 211, 238, 0.60); }
        .lb-left { left: 16px; }
        .lb-right { right: 16px; }

        .lb-stage {
          position: absolute;
          inset: 0;
          padding: 56px 72px 66px 72px;
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 10;
        }
        .lb-img {
          max-width: 100%;
          max-height: 100%;
          object-fit: contain;
          filter: drop-shadow(0 0 18px rgba(34, 211, 238, 0.10));
          user-select: none;
        }
        .lb-footer {
          position: absolute;
          left: 14px;
          right: 14px;
          bottom: 14px;
          z-index: 20;
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 12px;
          padding: 10px 12px;
          border-radius: 14px;
          border: 1px solid rgba(255,255,255,0.10);
          background: rgba(9, 9, 11, 0.35);
          backdrop-filter: blur(10px);
        }

        .scanlines {
          background: repeating-linear-gradient(
            to bottom,
            rgba(255,255,255,0.03),
            rgba(255,255,255,0.03) 1px,
            rgba(255,255,255,0.0) 2px,
            rgba(255,255,255,0.0) 6px
          );
          mix-blend-mode: overlay;
        }

        @keyframes slideInRight {
          0% { opacity: 0; transform: translateX(18px) scale(0.995); filter: blur(2px); }
          100% { opacity: 1; transform: translateX(0) scale(1); filter: blur(0); }
        }
        @keyframes slideInLeft {
          0% { opacity: 0; transform: translateX(-18px) scale(0.995); filter: blur(2px); }
          100% { opacity: 1; transform: translateX(0) scale(1); filter: blur(0); }
        }
        .slide-in-right { animation: slideInRight 220ms ease; }
        .slide-in-left { animation: slideInLeft 220ms ease; }

        @media (prefers-reduced-motion: reduce) {
          .warp-canvas { display: none; }
          .slide-in-right, .slide-in-left { animation: none !important; }
        }
      `}</style>

      <div className="relative z-10 max-w-4xl mx-auto px-6 py-12">
        <header className="text-center mb-12">
          <div className="inline-block mb-6 relative">
            <div
              className="absolute inset-0 w-44 h-44 -m-4 rounded-full"
              style={{
                background: "conic-gradient(from 0deg, #ec4899, #8b5cf6, #3b82f6, #06b6d4, #ec4899)",
                animation: "glow-pulse 4s ease-in-out infinite",
                filter: "blur(15px)",
                opacity: 0.6,
              }}
            />
            <div className="relative w-36 h-36 rounded-full flex items-center justify-center" style={{ animation: "glow-pulse 3s ease-in-out infinite" }}>
              <div className="w-32 h-32 flex items-center justify-center" style={{ animation: "pegasus-float 4s ease-in-out infinite" }}>
                <img src="/images/pegasus.png?v=2" alt="Zo Computer" className="w-28 h-28 object-contain" />
              </div>
            </div>
          </div>

          <h1 className="text-2xl font-semibold mb-4">
            <span className="bg-gradient-to-r from-pink-400 via-purple-400 to-blue-400 bg-clip-text text-transparent">DaGreatGAWDNYC</span>
          </h1>
          <h2 className="text-4xl md:text-5xl font-bold leading-relaxed pb-1 mb-4">
            <span className="bg-gradient-to-r from-pink-400 via-purple-400 to-blue-400 bg-clip-text text-transparent">Designer. Musician. Technologist.</span>
          </h2>
          <div className="flex items-center justify-center gap-2 mb-4">
            <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
            <p className="text-zinc-400">Self-taught · always building</p>
          </div>
          <p className="text-zinc-400 text-base max-w-2xl mx-auto leading-relaxed">
            I'm a clothing designer and music artist with a big love for tech. I'm self-taught and always tinkering, especially with cybersecurity, AI, and creative tools. I've been teaching myself prompt engineering too, still learning every day.
          </p>
        </header>

        <section className="mb-16">
          <h3 className="text-pink-400 text-sm tracking-[0.2em] mb-6 text-center">WHAT I'M INTO</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {passions.map((passion, i) => {
              const hasLinks = passion.links && passion.links.length > 0;
              const hasCarousel = false;
              const expandable = hasLinks || hasCarousel;
              const isExpanded = expandedPassion === passion.title;

              return (
                <div
                  key={i}
                  className={
                    "bg-zinc-900/60 border border-zinc-800/50 rounded-xl backdrop-blur-sm overflow-hidden transition-all duration-300 " +
                    (expandable ? "cursor-pointer hover:border-pink-500/50 hover:bg-zinc-900/80 " : "") +
                    (isExpanded ? "border-pink-500/50" : "")
                  }
                  onClick={() => expandable && setExpandedPassion(isExpanded ? null : passion.title)}
                >
                  <div className={"p-4 " + (expandable ? "pb-2" : "")}>
                    <div className="flex items-start justify-between">
                      <div>
                        <div className="text-2xl mb-2">{passion.emoji}</div>
                        <h4 className="text-white font-medium mb-1">{passion.title}</h4>
                      </div>
                      {expandable && (
                        <div className="mt-1">{isExpanded ? <ChevronDown className="w-4 h-4 text-zinc-400" /> : <ChevronRight className="w-4 h-4 text-zinc-400" />}</div>
                      )}
                    </div>
                    <p className="text-zinc-500 text-sm">{passion.description}</p>
                    {expandable && !isExpanded && <p className="text-pink-400/60 text-xs mt-2">Click to see more →</p>}
                  </div>

                  {isExpanded && expandable && (
                    <div className="border-t border-zinc-800/50 bg-zinc-950/30 p-4">
                      {hasCarousel && <DesignCarousel photos={DESIGN_PHOTOS} onOpen={(i2) => setDesignLightbox(i2)} />}

                      {hasLinks && (
                        <div className={hasCarousel ? "mt-4" : ""}>
                          <div className="space-y-2">
                            {passion.links.map((link, j) => (
                              <a
                                key={j}
                                href={link.url}
                                target={link.url.startsWith("/") ? undefined : "_blank"}
                                rel={link.url.startsWith("/") ? undefined : "noopener noreferrer"}
                                className="flex items-center justify-between gap-2 text-sm text-zinc-300 hover:text-pink-400 transition-colors py-1.5 px-2 rounded hover:bg-zinc-800/30"
                                onClick={(e) => e.stopPropagation()}
                              >
                                <span>{link.name}</span>
                                {!link.url.startsWith("/") && <ExternalLink className="w-3 h-3 text-zinc-500" />}
                              </a>
                            ))}
                          </div>
                          {(passion as any).footer && <p className="text-zinc-500 text-xs mt-3 italic">{(passion as any).footer}</p>}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        <section className="mb-16">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-pink-400 text-sm tracking-[0.2em] text-center flex-1">MY FILES</h3>
            <span className="text-zinc-600 text-xs">🔒 Private</span>
          </div>

          {!savedKey ? (
            <div className="bg-zinc-900/60 border border-zinc-800/50 rounded-xl p-6 backdrop-blur-sm">
              <p className="text-zinc-300 text-sm mb-4">Add your access key to view files</p>
              <div className="flex gap-2">
                <input
                  type="password"
                  value={accessKey}
                  onChange={(e) => setAccessKey(e.target.value)}
                  placeholder="Paste your access key..."
                  className="flex-1 bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white placeholder-zinc-500"
                />
                <button
                  onClick={saveKey}
                  className="bg-pink-600 hover:bg-pink-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition"
                >
                  Save
                </button>
              </div>
            </div>
          ) : (
            <>
              <div className="flex gap-2 mb-6 flex-wrap justify-center">
                {(["default", "recent", "types", "projects"] as const).map((group) => (
                  <button
                    key={group}
                    onClick={() => setGroupBy(group)}
                    className={`px-3 py-1.5 rounded text-sm font-medium transition ${
                      groupBy === group
                        ? "bg-pink-600 text-white"
                        : "bg-zinc-800 text-zinc-300 hover:bg-zinc-700"
                    }`}
                  >
                    {group === "default" ? "All" : group.charAt(0).toUpperCase() + group.slice(1)}
                  </button>
                ))}
              </div>

              {loading && (
                <div className="text-center py-8 text-zinc-400">
                  Loading files...
                </div>
              )}

              {error && (
                <div className="bg-red-900/20 border border-red-800/50 rounded-xl p-4 mb-4 text-sm text-red-300">
                  {error}
                  <button
                    onClick={clearKey}
                    className="block mt-2 text-xs text-red-400 hover:text-red-300 underline"
                  >
                    Clear and re-enter key
                  </button>
                </div>
              )}

              {!loading && !error && fileCategories.length === 0 && (
                <div className="text-center py-8 text-zinc-500">
                  No files found
                </div>
              )}

              <div className="space-y-2">
                {fileCategories.map((category, i) => {
                  const isExpanded = expandedCategory === category.name;
                  const Icon = File;
                  return (
                    <div key={i} className="bg-zinc-900/60 border border-zinc-800/50 rounded-xl backdrop-blur-sm overflow-hidden">
                      <button
                        onClick={() => setExpandedCategory(isExpanded ? null : category.name)}
                        className="w-full flex items-center justify-between p-4 hover:border-pink-500/50 transition-colors"
                      >
                        <div className="flex items-center gap-3">
                          <Folder className="w-5 h-5 text-cyan-400" />
                          <span className="text-white font-medium">{category.name}</span>
                          <span className="text-zinc-500 text-sm">({(category.files || []).length})</span>
                        </div>
                        {isExpanded ? <ChevronDown className="w-5 h-5 text-zinc-400" /> : <ChevronRight className="w-5 h-5 text-zinc-400" />}
                      </button>
                      {isExpanded && (category.files || []).length > 0 && (
                        <div className="border-t border-zinc-800/50 bg-zinc-950/30 max-h-64 overflow-y-auto">
                          {(category.files || []).slice(0, 20).map((file, j) => (
                            <a
                              key={j}
                              href={"/?t=search&q=" + encodeURIComponent(file.path)}
                              className="flex items-center gap-2 px-4 py-2.5 hover:bg-zinc-800/30 transition-colors text-sm border-b border-zinc-800/30 last:border-b-0"
                            >
                              <File className="w-4 h-4 text-zinc-500 flex-shrink-0" />
                              <span className="text-zinc-300 truncate">{file.name}</span>
                            </a>
                          ))}
                          {(category.files || []).length > 20 && (
                            <div className="px-4 py-2 text-xs text-zinc-500">
                              +{(category.files || []).length - 20} more...
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </>
          )}
        </section>

        <section className="mb-16">
          <h3 className="text-pink-400 text-sm tracking-[0.2em] mb-6 text-center">SKILLS & PROJECTS</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {projects.map((project, i) => {
              const Icon = project.icon;
              return (
                <a
                  key={i}
                  href={project.link || "#"}
                  target={project.link && !project.link.startsWith("/") ? "_blank" : undefined}
                  rel={project.link && !project.link.startsWith("/") ? "noopener noreferrer" : undefined}
                  className={
                    "bg-zinc-900/60 border border-zinc-800/50 rounded-xl p-6 " +
                    (project.link ? "hover:border-pink-500/50 transition-colors group cursor-pointer" : "opacity-75") +
                    " backdrop-blur-sm"
                  }
                >
                  <div className="flex items-center justify-between mb-3">
                    <Icon className="w-6 h-6 text-cyan-400" />
                    {project.link && <ExternalLink className="w-4 h-4 text-zinc-600 group-hover:text-zinc-400 transition-colors" />}
                  </div>
                  <h4 className="text-white font-medium mb-1">{project.title}</h4>
                  <p className="text-zinc-500 text-sm">{project.description}</p>
                </a>
              );
            })}
          </div>
        </section>

        <section className="mb-16">
          <h3 className="text-pink-400 text-sm tracking-[0.2em] mb-6 text-center">CONNECT</h3>
          <div className="flex justify-center gap-4">
            <a href="mailto:dagawdnyc@zo.computer" className="flex items-center gap-2 bg-zinc-900/60 border border-zinc-800/50 rounded-lg px-6 py-3 hover:border-pink-500/50 transition-colors backdrop-blur-sm">
              <Mail className="w-5 h-5 text-zinc-400" />
              <span className="text-zinc-300">Email</span>
            </a>
            <a href="https://www.instagram.com/kaiyzernomics4life" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 bg-zinc-900/60 border border-zinc-800/50 rounded-lg px-6 py-3 hover:border-pink-500/50 transition-colors backdrop-blur-sm">
              <Instagram className="w-5 h-5 text-zinc-400" />
              <span className="text-zinc-300">Instagram</span>
            </a>
          </div>
        </section>

        <footer className="text-center pt-8 border-t border-zinc-800/50">
          <p className="text-sm text-zinc-400 mb-1">
            Built by <span className="bg-gradient-to-r from-purple-400 via-pink-400 to-cyan-400 bg-clip-text text-transparent font-semibold">DaGreatGAWDNYC</span>
          </p>
          <p className="text-sm text-zinc-500">
            Built with <span className="bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent font-semibold">Zo Computer</span>
          </p>
          <p className="text-zinc-700 text-xs mt-1">⢕⣿⢀⣏⣿⢳⡕⣆⢺⣋⢟</p>
        </footer>
      </div>

      <DesignLightbox photos={DESIGN_PHOTOS} index={designLightbox} onClose={() => setDesignLightbox(null)} />
    </div>
  );
}
