// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ChevronLeft, ChevronRight, ExternalLink, Maximize2, X, Shuffle } from "lucide-react";

const DESIGN_PHOTOS = [
  "/design-photos/design-01.jpg",
  "/design-photos/design-02.jpg",
  "/design-photos/design-03.jpg",
  "/design-photos/design-04.jpg",
  "/design-photos/design-05.jpg",
  "/design-photos/design-06.png",
  "/design-photos/design-07.png",
  "/design-photos/design-08.jpg",
  "/design-photos/design-09.jpg",
  "/design-photos/design-10.jpg",
  "/design-photos/design-11.jpg",
  "/design-photos/design-12.jpg",
  "/design-photos/design-13.jpg",
  "/design-photos/design-14.jpg",
  "/design-photos/design-15.jpg",
  "/design-photos/design-16.jpg",
  "/design-photos/design-17.jpg",
  "/design-photos/design-18.png",
  "/design-photos/design-19.jpg",
  "/design-photos/design-20.png",
  "/design-photos/design-21.png",
  "/design-photos/design-22.jpg",
  "/design-photos/design-23.jpg",
  "/design-photos/design-24.jpg",
  "/design-photos/design-25.jpg",
  "/design-photos/design-26.jpg",
  "/design-photos/design-27.jpg",
  "/design-photos/design-28.jpg",
  "/design-photos/design-29.jpg",
  "/design-photos/design-30.jpg",
  "/design-photos/design-31.jpg",
  "/design-photos/design-32.jpg",
  "/design-photos/design-33.jpg",
  "/design-photos/design-34.jpg",
  "/design-photos/design-35.jpg",
  "/design-photos/design-36.jpg",
  "/design-photos/design-37.jpg",
  "/design-photos/design-38.jpg",
  "/design-photos/design-39.jpg",
  "/design-photos/design-40.jpg",
  "/design-photos/design-41.jpg",
  "/design-photos/design-42.jpg",
  "/design-photos/design-43.jpg",
  "/design-photos/design-44.jpg",
  "/design-photos/design-45.jpg",
  "/design-photos/design-46.jpg",
  "/design-photos/design-47.jpg",
  "/design-photos/design-48.jpg",
  "/design-photos/design-49.jpg",
  "/design-photos/design-50.png",
  "/design-photos/design-51.jpg",
  "/design-photos/design-52.png",
  "/design-photos/design-53.jpg",
  "/design-photos/design-54.jpg",
  "/design-photos/design-55.jpg",
  "/design-photos/design-56.jpg",
  "/design-photos/design-57.png",
  "/design-photos/design-58.png",
  "/design-photos/design-59.png",
  "/design-photos/design-60.jpg",
  "/design-photos/design-61.jpg",
  "/design-photos/design-62.png",
  "/design-photos/design-63.png",
  "/design-photos/design-64.jpg",
  "/design-photos/design-65.png",
  "/design-photos/design-66.png",
  "/design-photos/design-67.jpg",
  "/design-photos/design-68.png",
  "/design-photos/design-69.jpg",
  "/design-photos/design-70.png",
  "/design-photos/design-71.jpg",
  "/design-photos/design-72.png",
  "/design-photos/design-73.jpg",
  "/design-photos/design-74.jpg",
  "/design-photos/design-75.jpg",
  "/design-photos/design-76.png",
  "/design-photos/design-77.jpg",
  "/design-photos/design-78.jpg",
  "/design-photos/design-79.jpg",
  "/design-photos/design-80.jpg",
  "/design-photos/design-81.jpg",
  "/design-photos/design-82.jpg",
  "/design-photos/design-83.jpg",
  "/design-photos/design-84.jpg",
  "/design-photos/design-85.jpg",
  "/design-photos/design-86.png",
  "/design-photos/design-87.jpg",
  "/design-photos/design-88.jpg",
  "/design-photos/design-89.png",
];

function wrapIndex(i: number, len: number) {
  if (len <= 0) return 0;
  return ((i % len) + len) % len;
}

function StarfieldCanvas({ density = 1 }: { density?: number }) {
  const hostRef = useRef<HTMLDivElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const host = hostRef.current;
    const canvas = canvasRef.current;
    if (!host || !canvas) return;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const reduced = window.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches ?? false;

    const state = {
      w: 1,
      h: 1,
      dpr: 1,
      stars: [] as Array<{ x: number; y: number; r: number; a: number; s: number; p: number; hue: number }>,
      t0: performance.now(),
    };

    const draw = (t: number, dt: number, animate: boolean) => {
      ctx.clearRect(0, 0, state.w, state.h);
      ctx.globalCompositeOperation = "lighter";

      for (let i = 0; i < state.stars.length; i++) {
        const s = state.stars[i];

        if (animate) {
          s.y += s.s * dt * 26;
          if (s.y > state.h + 8) {
            s.y = -8;
            s.x = Math.random() * state.w;
          }
        }

        const tw = animate ? 0.55 + 0.45 * Math.sin(t * 0.0012 + s.p) : 1;
        const alpha = s.a * tw;

        ctx.beginPath();
        ctx.fillStyle = `hsla(${s.hue}, 90%, 78%, ${alpha})`;
        ctx.arc(s.x, s.y, s.r, 0, Math.PI * 2);
        ctx.fill();
      }

      ctx.globalCompositeOperation = "source-over";
    };

    const rebuildStars = () => {
      const base = 260 + (state.w * state.h) / 8000;
      const target = Math.floor(base * density);

      state.stars = Array.from({ length: target }).map(() => {
        const big = Math.random() < 0.06;
        const hue = 190 + Math.random() * 100;
        return {
          x: Math.random() * state.w,
          y: Math.random() * state.h,
          r: big ? 1.8 + Math.random() * 1.9 : 0.7 + Math.random() * 1.6,
          a: big ? 0.45 + Math.random() * 0.40 : 0.22 + Math.random() * 0.55,
          s: 0.10 + Math.random() * 0.55,
          p: Math.random() * Math.PI * 2,
          hue,
        };
      });
    };

    const resize = () => {
      const rect = host.getBoundingClientRect();
      state.w = Math.max(1, Math.floor(rect.width));
      state.h = Math.max(1, Math.floor(rect.height));
      state.dpr = Math.max(1, Math.min(2, window.devicePixelRatio || 1));
      canvas.width = Math.floor(state.w * state.dpr);
      canvas.height = Math.floor(state.h * state.dpr);
      canvas.style.width = state.w + "px";
      canvas.style.height = state.h + "px";
      ctx.setTransform(state.dpr, 0, 0, state.dpr, 0, 0);
      rebuildStars();
      draw(performance.now(), 0, false);
    };

    resize();

    let ro: ResizeObserver | null = null;
    const onWinResize = () => resize();
    if (typeof ResizeObserver !== "undefined") {
      ro = new ResizeObserver(() => resize());
      ro.observe(host);
    } else {
      window.addEventListener("resize", onWinResize);
    }

    let raf = 0;
    const tick = (t: number) => {
      if (!reduced) raf = requestAnimationFrame(tick);

      const dt = reduced ? 0 : Math.min(0.04, (t - state.t0) / 1000);
      state.t0 = t;
      draw(t, dt, !reduced);
    };

    if (reduced) tick(performance.now());
    else raf = requestAnimationFrame(tick);

    return () => {
      ro?.disconnect();
      window.removeEventListener("resize", onWinResize);
      if (raf) cancelAnimationFrame(raf);
    };
  }, [density]);

  return (
    <div ref={hostRef} className="absolute inset-0">
      <canvas ref={canvasRef} className="absolute inset-0" />
    </div>
  );
}

function DesignLightbox({
  photos,
  index,
  onClose,
}: {
  photos: string[];
  index: number | null;
  onClose: () => void;
}) {
  const [idx, setIdx] = useState(0);

  useEffect(() => {
    if (index === null) return;
    setIdx(wrapIndex(index, photos.length));
  }, [index, photos.length]);

  useEffect(() => {
    if (index === null) return;

    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
      if (e.key === "ArrowLeft") setIdx((v) => wrapIndex(v - 1, photos.length));
      if (e.key === "ArrowRight") setIdx((v) => wrapIndex(v + 1, photos.length));
    };

    window.addEventListener("keydown", onKey);
    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = prevOverflow;
    };
  }, [index, onClose, photos.length]);

  if (index === null) return null;

  const current = photos[idx] || "";

  return (
    <div className="lb-backdrop" role="dialog" aria-modal="true" aria-label="Design photos" onClick={onClose}>
      <div className="lb-panel" onClick={(e) => e.stopPropagation()}>
        <div className="lb-lcars-bar">
          <div className="lb-lcars-left">
            <div className="lb-lcars-pill lb-lcars-orange">
              <div className="lb-lcars-pill-title">DESIGN</div>
              <div className="lb-lcars-pill-sub">FULLSCREEN</div>
            </div>
            <div className="lb-lcars-pill lb-lcars-purple">
              <div className="lb-lcars-pill-title">{idx + 1} / {photos.length}</div>
              <div className="lb-lcars-pill-sub">INDEX</div>
            </div>
          </div>

          <button className="lb-close" onClick={onClose} aria-label="Close">
            <X className="w-5 h-5" />
          </button>
        </div>

        <button className="lb-nav lb-left" onClick={() => setIdx((v) => wrapIndex(v - 1, photos.length))} aria-label="Previous">
          <ChevronLeft className="w-6 h-6" />
        </button>
        <button className="lb-nav lb-right" onClick={() => setIdx((v) => wrapIndex(v + 1, photos.length))} aria-label="Next">
          <ChevronRight className="w-6 h-6" />
        </button>

        <div className="lb-stage">
          <img src={current} alt={`Design ${idx + 1}`} className="lb-img" draggable={false} />
        </div>

        <div className="lb-footer">
          <div className="flex items-center gap-2">
            <span className="lcars-dot" />
            <span className="text-xs text-zinc-200 tracking-wide">Design</span>
            <span className="text-zinc-500 text-xs">{idx + 1} / {photos.length}</span>
          </div>
          <div className="text-[11px] text-zinc-500">Esc to close, arrows to navigate</div>
        </div>
      </div>
    </div>
  );
}

export default function Design() {
  const [idx, setIdx] = useState(0);
  const [dir, setDir] = useState<1 | -1>(1);
  const [lightbox, setLightbox] = useState<number | null>(null);
  const stageRef = useRef<HTMLDivElement | null>(null);

  const current = DESIGN_PHOTOS[idx] || "";

  const go = (next: number, nextDir: 1 | -1) => {
    setDir(nextDir);
    setIdx(wrapIndex(next, DESIGN_PHOTOS.length));
  };

  const prev = () => go(idx - 1, -1);
  const next = () => go(idx + 1, 1);

  const random = () => {
    if (!DESIGN_PHOTOS.length) return;
    const r = Math.floor(Math.random() * DESIGN_PHOTOS.length);
    setDir(r >= idx ? 1 : -1);
    setIdx(r);
  };

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowLeft") prev();
      if (e.key === "ArrowRight") next();
      if (e.key === "Home") {
        setDir(-1);
        setIdx(0);
      }
      if (e.key === "End") {
        setDir(1);
        setIdx(DESIGN_PHOTOS.length - 1);
      }
      if (e.key.toLowerCase() === "r") random();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [idx]);

  useEffect(() => {
    const el = stageRef.current;
    if (!el) return;

    let startX = 0;
    let startY = 0;
    let active = false;

    const onDown = (e: PointerEvent) => {
      active = true;
      startX = e.clientX;
      startY = e.clientY;
    };

    const onUp = (e: PointerEvent) => {
      if (!active) return;
      active = false;
      const dx = e.clientX - startX;
      const dy = e.clientY - startY;
      if (Math.abs(dx) < 30 || Math.abs(dx) < Math.abs(dy)) return;
      if (dx > 0) prev();
      else next();
    };

    el.addEventListener("pointerdown", onDown);
    el.addEventListener("pointerup", onUp);

    return () => {
      el.removeEventListener("pointerdown", onDown);
      el.removeEventListener("pointerup", onUp);
    };
  }, [idx]);

  return (
    <div className="min-h-screen text-white relative overflow-hidden bg-black">
      <div className="fixed inset-0 z-0 pointer-events-none">
        <div className="absolute inset-0 bg-black" />
        <StarfieldCanvas density={1.25} />
        <div className="absolute inset-0 nebula" />
        <div className="planet planet-a ring" />
        <div className="planet planet-b" />
        <div className="absolute inset-0 opacity-[0.05]" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,.10) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.10) 1px, transparent 1px)", backgroundSize: "72px 72px" }} />
        <div className="absolute inset-0 scanlines" />
        <div className="absolute inset-0" style={{ background: "radial-gradient(1200px 700px at 50% 30%, rgba(0,0,0,0.0), rgba(0,0,0,0.62) 70%, rgba(0,0,0,0.88) 100%)" }} />
      </div>

      <style>{`
        .nebula {
          opacity: 0.78;
          mix-blend-mode: screen;
          background:
            radial-gradient(1200px 680px at 22% 18%, rgba(110, 231, 245, 0.12), transparent 62%),
            radial-gradient(1000px 620px at 78% 76%, rgba(183, 161, 255, 0.13), transparent 64%),
            radial-gradient(900px 520px at 62% 22%, rgba(255, 177, 85, 0.10), transparent 58%),
            conic-gradient(from 210deg at 55% 45%, rgba(183,161,255,0.00), rgba(110,231,245,0.06), rgba(255,177,85,0.05), rgba(183,161,255,0.00));
          animation: nebula-drift 22s ease-in-out infinite;
        }

        @keyframes nebula-drift {
          0% { transform: translate3d(-10px, 8px, 0) scale(1.02); opacity: 0.70; }
          50% { transform: translate3d(12px, -6px, 0) scale(1.05); opacity: 0.88; }
          100% { transform: translate3d(-10px, 8px, 0) scale(1.02); opacity: 0.70; }
        }

        .scanlines {
          opacity: 0.70;
          background: repeating-linear-gradient(
            to bottom,
            rgba(255,255,255,0.024),
            rgba(255,255,255,0.024) 1px,
            rgba(255,255,255,0.0) 2px,
            rgba(255,255,255,0.0) 7px
          );
          mix-blend-mode: overlay;
        }

        .planet {
          position: absolute;
          border-radius: 9999px;
          filter: saturate(1.05);
          opacity: 0.98;
        }

        .planet-a {
          width: 270px;
          height: 270px;
          left: -70px;
          top: 120px;
          background:
            radial-gradient(circle at 35% 35%, rgba(255, 235, 205, 0.85), rgba(255, 177, 85, 0.40) 38%, rgba(88, 35, 12, 0.18) 72%, rgba(0,0,0,0.0) 74%),
            radial-gradient(circle at 65% 62%, rgba(183, 161, 255, 0.18), rgba(0,0,0,0.0) 60%);
          box-shadow: 0 0 0 1px rgba(255, 172, 76, 0.12) inset, 0 0 80px rgba(255, 172, 76, 0.10);
          animation: planet-float-a 18s ease-in-out infinite;
        }

        .planet-b {
          width: 205px;
          height: 205px;
          right: -46px;
          bottom: 160px;
          background:
            radial-gradient(circle at 30% 30%, rgba(220, 235, 255, 0.82), rgba(110, 231, 245, 0.24) 40%, rgba(0,0,0,0.18) 72%, rgba(0,0,0,0.0) 74%),
            radial-gradient(circle at 70% 70%, rgba(183, 161, 255, 0.18), rgba(0,0,0,0.0) 55%);
          box-shadow: 0 0 0 1px rgba(110, 231, 245, 0.12) inset, 0 0 70px rgba(183, 161, 255, 0.10);
          animation: planet-float-b 22s ease-in-out infinite;
        }

        @keyframes planet-float-a {
          0% { transform: translate3d(0, 0, 0) scale(1); }
          50% { transform: translate3d(12px, -10px, 0) scale(1.02); }
          100% { transform: translate3d(0, 0, 0) scale(1); }
        }

        @keyframes planet-float-b {
          0% { transform: translate3d(0, 0, 0) scale(1); }
          50% { transform: translate3d(-10px, 10px, 0) scale(1.02); }
          100% { transform: translate3d(0, 0, 0) scale(1); }
        }

        .ring:before {
          content: "";
          position: absolute;
          inset: -24px;
          border-radius: 9999px;
          background: radial-gradient(closest-side, rgba(0,0,0,0.0), rgba(0,0,0,0.0) 55%, rgba(255, 172, 76, 0.12) 57%, rgba(255, 172, 76, 0.0) 70%);
          transform: rotate(-18deg);
          opacity: 0.85;
        }

        .lcars-dot {
          width: 6px;
          height: 6px;
          border-radius: 999px;
          background: rgba(255, 172, 76, 0.95);
          box-shadow: 0 0 12px rgba(255, 172, 76, 0.55);
        }

        .lcars-shell {
          border-radius: 18px;
          overflow: hidden;
          border: 1px solid rgba(255, 172, 76, 0.22);
          background: rgba(6, 6, 8, 0.64);
          box-shadow: 0 0 0 1px rgba(187, 130, 255, 0.08) inset, 0 0 44px rgba(255, 172, 76, 0.06);
          backdrop-filter: blur(10px);
        }

        .lcars-top {
          display: flex;
          gap: 10px;
          padding: 12px;
          background: rgba(0,0,0,0.18);
          border-bottom: 1px solid rgba(255,255,255,0.06);
        }

        .lcars-top-right {
          display: flex;
          gap: 10px;
          flex: 1;
          justify-content: flex-end;
          min-width: 0;
        }

        .lcars-pill {
          border-radius: 999px;
          padding: 10px 14px;
          display: flex;
          flex-direction: column;
          justify-content: center;
          color: rgba(5,5,6,0.92);
          box-shadow: 0 0 0 1px rgba(255,255,255,0.10) inset;
          user-select: none;
          min-width: 0;
        }

        .lcars-pill-btn {
          cursor: pointer;
          border: none;
          text-align: left;
        }

        .lcars-pill-title {
          font-size: 12px;
          font-weight: 900;
          letter-spacing: 0.08em;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }

        .lcars-pill-sub {
          font-size: 10px;
          letter-spacing: 0.12em;
          opacity: 0.82;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }

        .lcars-orange { background: #ffb155; }
        .lcars-yellow { background: #ffd37a; }
        .lcars-purple { background: #b7a1ff; }
        .lcars-lavender { background: #d7ccff; }
        .lcars-cyan { background: #6ee7f5; }

        .lcars-chip {
          display: inline-flex;
          align-items: center;
          gap: 10px;
          border-radius: 999px;
          padding: 10px 14px;
          color: rgba(5,5,6,0.92);
          box-shadow: 0 0 0 1px rgba(255,255,255,0.10) inset;
          text-decoration: none;
          user-select: none;
        }
        .lcars-chip:hover { filter: brightness(1.03); }

        .lcars-main {
          display: grid;
          grid-template-columns: 140px 1fr;
          gap: 12px;
          padding: 12px;
        }

        .lcars-rail {
          display: flex;
          flex-direction: column;
          gap: 10px;
        }

        .lcars-rail-btn {
          border: none;
          border-radius: 18px;
          padding: 12px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          color: rgba(5,5,6,0.92);
          box-shadow: 0 0 0 1px rgba(255,255,255,0.10) inset;
          transition: transform 120ms ease, filter 120ms ease;
        }

        .lcars-rail-btn:hover { transform: scale(1.02); filter: brightness(1.02); }
        .lcars-rail-btn:active { transform: scale(0.99); }

        .lcars-rail-label {
          font-size: 12px;
          font-weight: 900;
          letter-spacing: 0.10em;
        }

        .lcars-rail-cap {
          border-radius: 18px;
          padding: 14px 12px;
          box-shadow: 0 0 0 1px rgba(255,255,255,0.10) inset;
          color: rgba(5,5,6,0.92);
          margin-top: auto;
        }

        .lcars-rail-cap-title {
          font-size: 12px;
          font-weight: 900;
          letter-spacing: 0.10em;
        }

        .lcars-rail-cap-sub {
          font-size: 10px;
          letter-spacing: 0.12em;
          opacity: 0.82;
        }

        .lcars-stage {
          position: relative;
          border-radius: 16px;
          overflow: hidden;
          border: 1px solid rgba(255,255,255,0.08);
          background: rgba(0,0,0,0.25);
          aspect-ratio: 16 / 9;
        }

        .lcars-stage-bg {
          position: absolute;
          inset: 0;
          background:
            radial-gradient(900px 300px at 50% 0%, rgba(255, 172, 76, 0.11), transparent 60%),
            linear-gradient(90deg, rgba(255,172,76,0.0), rgba(187,130,255,0.08), rgba(110,231,245,0.06), rgba(255,172,76,0.0)),
            repeating-linear-gradient(to bottom, rgba(255,255,255,0.03), rgba(255,255,255,0.03) 1px, rgba(255,255,255,0.0) 2px, rgba(255,255,255,0.0) 6px);
          mix-blend-mode: overlay;
          opacity: 0.80;
          pointer-events: none;
        }

        .lcars-img {
          position: absolute;
          inset: 0;
          width: 100%;
          height: 100%;
          object-fit: contain;
          padding: 10px;
          image-orientation: from-image;
          filter: drop-shadow(0 0 18px rgba(255, 172, 76, 0.10));
        }

        .lcars-stage-hud {
          position: absolute;
          left: 10px;
          bottom: 10px;
          display: inline-flex;
          align-items: center;
          gap: 8px;
          border-radius: 999px;
          padding: 8px 10px;
          border: 1px solid rgba(255,255,255,0.10);
          background: rgba(9, 9, 11, 0.35);
          backdrop-filter: blur(10px);
        }

        .lcars-hud-text {
          font-size: 10px;
          letter-spacing: 0.12em;
          color: rgba(255,255,255,0.82);
        }

        .lcars-bottom {
          padding: 12px;
          border-top: 1px solid rgba(255,255,255,0.06);
          background: rgba(0,0,0,0.14);
        }

        .lcars-bottom-label {
          font-size: 11px;
          letter-spacing: 0.14em;
          color: rgba(255,255,255,0.70);
        }

        .lcars-bottom-meta {
          font-size: 11px;
          color: rgba(161, 161, 170, 0.95);
        }

        .lcars-grid {
          margin-top: 10px;
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(92px, 1fr));
          gap: 8px;
          max-height: 360px;
          overflow: auto;
          padding-right: 6px;
        }

        .lcars-thumb {
          border-radius: 14px;
          overflow: hidden;
          border: 1px solid rgba(255,255,255,0.10);
          background: rgba(9, 9, 11, 0.35);
          transition: transform 120ms ease, border-color 120ms ease;
          aspect-ratio: 16 / 10;
        }

        .lcars-thumb:hover { transform: scale(1.02); border-color: rgba(255, 172, 76, 0.34); }
        .lcars-thumb.active { border-color: rgba(255, 172, 76, 0.70); box-shadow: 0 0 0 1px rgba(187,130,255,0.10) inset, 0 0 18px rgba(255, 172, 76, 0.08); }

        @keyframes slideInRight {
          0% { opacity: 0; transform: translateX(18px) scale(0.995); filter: blur(2px); }
          100% { opacity: 1; transform: translateX(0) scale(1); filter: blur(0); }
        }
        @keyframes slideInLeft {
          0% { opacity: 0; transform: translateX(-18px) scale(0.995); filter: blur(2px); }
          100% { opacity: 1; transform: translateX(0) scale(1); filter: blur(0); }
        }
        .slide-in-right { animation: slideInRight 220ms ease; }
        .slide-in-left { animation: slideInLeft 220ms ease; }

        .lb-backdrop {
          position: fixed;
          inset: 0;
          z-index: 60;
          background: rgba(0,0,0,0.86);
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 20px;
        }

        .lb-panel {
          position: relative;
          width: min(1100px, calc(100vw - 40px));
          height: min(720px, calc(100vh - 40px));
          border-radius: 18px;
          overflow: hidden;
          border: 1px solid rgba(255, 172, 76, 0.28);
          background: rgba(6, 6, 8, 0.72);
          box-shadow: 0 0 0 1px rgba(187, 130, 255, 0.10) inset, 0 0 58px rgba(255, 172, 76, 0.08);
          backdrop-filter: blur(14px);
        }

        .lb-panel:before {
          content: "";
          position: absolute;
          inset: 0;
          background:
            radial-gradient(900px 300px at 50% 0%, rgba(255, 172, 76, 0.14), transparent 60%),
            linear-gradient(90deg, rgba(255,172,76,0.0), rgba(187,130,255,0.10), rgba(46,213,245,0.06), rgba(255,172,76,0.0));
          opacity: 0.9;
          pointer-events: none;
        }

        .lb-panel:after {
          content: "";
          position: absolute;
          inset: 0;
          background: repeating-linear-gradient(
            to bottom,
            rgba(255,255,255,0.03),
            rgba(255,255,255,0.03) 1px,
            rgba(255,255,255,0.0) 2px,
            rgba(255,255,255,0.0) 6px
          );
          mix-blend-mode: overlay;
          opacity: 0.65;
          pointer-events: none;
        }

        .lb-lcars-bar {
          position: absolute;
          left: 14px;
          right: 14px;
          top: 14px;
          z-index: 30;
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 12px;
        }

        .lb-lcars-left {
          display: flex;
          align-items: stretch;
          gap: 10px;
          min-width: 0;
        }

        .lb-lcars-pill {
          border-radius: 999px;
          padding: 10px 14px;
          display: flex;
          flex-direction: column;
          justify-content: center;
          color: rgba(5,5,6,0.92);
          box-shadow: 0 0 0 1px rgba(255,255,255,0.10) inset;
          user-select: none;
        }

        .lb-lcars-pill-title {
          font-size: 12px;
          font-weight: 800;
          letter-spacing: 0.08em;
        }

        .lb-lcars-pill-sub {
          font-size: 10px;
          letter-spacing: 0.12em;
          opacity: 0.8;
        }

        .lb-lcars-orange { background: #ffb155; }
        .lb-lcars-purple { background: #b7a1ff; }

        .lb-close {
          width: 44px;
          height: 44px;
          border-radius: 16px;
          border: 1px solid rgba(255,255,255,0.12);
          background: rgba(9, 9, 11, 0.35);
          color: rgba(255,255,255,0.86);
          display: inline-flex;
          align-items: center;
          justify-content: center;
          backdrop-filter: blur(10px);
        }
        .lb-close:hover { border-color: rgba(255, 172, 76, 0.55); }

        .lb-nav {
          position: absolute;
          top: 50%;
          transform: translateY(-50%);
          z-index: 30;
          width: 56px;
          height: 56px;
          border-radius: 18px;
          border: 1px solid rgba(255, 172, 76, 0.32);
          background: rgba(9, 9, 11, 0.50);
          color: rgba(255,255,255,0.92);
          box-shadow: 0 0 0 1px rgba(187,130,255,0.10) inset, 0 0 34px rgba(255, 172, 76, 0.08);
          backdrop-filter: blur(12px);
        }
        .lb-nav:hover { border-color: rgba(255, 172, 76, 0.62); }
        .lb-left { left: 16px; }
        .lb-right { right: 16px; }

        .lb-stage {
          position: absolute;
          inset: 0;
          padding: 78px 72px 66px 72px;
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 10;
        }

        .lb-img {
          max-width: 100%;
          max-height: 100%;
          object-fit: contain;
          image-orientation: from-image;
          filter: drop-shadow(0 0 18px rgba(255, 172, 76, 0.10));
          user-select: none;
        }

        .lb-footer {
          position: absolute;
          left: 14px;
          right: 14px;
          bottom: 14px;
          z-index: 20;
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 12px;
          padding: 10px 12px;
          border-radius: 14px;
          border: 1px solid rgba(255,255,255,0.10);
          background: rgba(9, 9, 11, 0.35);
          backdrop-filter: blur(10px);
        }

        @media (max-width: 680px) {
          .lcars-main { grid-template-columns: 1fr; }
          .lcars-rail { flex-direction: row; }
          .lcars-rail-cap { display: none; }
          .lb-stage { padding: 74px 18px 62px 18px; }
          .planet-a { display: none; }
        }

        @media (prefers-reduced-motion: reduce) {
          .slide-in-right, .slide-in-left { animation: none !important; }
          .nebula, .planet-a, .planet-b { animation: none !important; }
        }
      `}</style>

      <div className="relative z-10 max-w-6xl mx-auto px-6 py-10">
        <div className="flex items-center justify-between gap-3 mb-6">
          <div className="flex items-center gap-2">
            <a href="/demo" className="lcars-chip lcars-orange">
              <ArrowLeft className="w-4 h-4" />
              <span className="text-sm font-semibold tracking-wide">BACK</span>
            </a>
            <a href="/" className="lcars-chip lcars-purple">
              <ExternalLink className="w-4 h-4" />
              <span className="text-sm font-semibold tracking-wide">HOME</span>
            </a>
          </div>

          <div className="lcars-chip lcars-lavender">
            <span className="lcars-dot" />
            <span className="text-sm font-semibold tracking-wide">{idx + 1} / {DESIGN_PHOTOS.length}</span>
          </div>
        </div>

        <div className="lcars-shell">
          <div className="lcars-top">
            <div className="lcars-pill lcars-orange">
              <div className="lcars-pill-title">DESIGN GALLERY</div>
              <div className="lcars-pill-sub">LCARS MODE</div>
            </div>

            <div className="lcars-top-right">
              <div className="lcars-pill lcars-purple">
                <div className="lcars-pill-title">NAV</div>
                <div className="lcars-pill-sub">ARROWS, SWIPE</div>
              </div>

              <button className="lcars-pill lcars-cyan lcars-pill-btn" onClick={() => setLightbox(idx)} aria-label="Open fullscreen">
                <div className="flex items-center gap-2">
                  <Maximize2 className="w-4 h-4" />
                  <span className="text-sm font-semibold">OPEN</span>
                </div>
                <div className="lcars-pill-sub">FULLSCREEN</div>
              </button>
            </div>
          </div>

          <div className="lcars-main">
            <div className="lcars-rail">
              <button className="lcars-rail-btn lcars-purple" onClick={prev} aria-label="Previous">
                <span className="lcars-rail-label">PREV</span>
                <ChevronLeft className="w-5 h-5" />
              </button>
              <button className="lcars-rail-btn lcars-orange" onClick={next} aria-label="Next">
                <span className="lcars-rail-label">NEXT</span>
                <ChevronRight className="w-5 h-5" />
              </button>
              <button className="lcars-rail-btn lcars-yellow" onClick={random} aria-label="Random">
                <span className="lcars-rail-label">RAND</span>
                <Shuffle className="w-5 h-5" />
              </button>

              <div className="lcars-rail-cap lcars-lavender">
                <div className="lcars-rail-cap-title">STATUS</div>
                <div className="lcars-rail-cap-sub">ONLINE</div>
              </div>
            </div>

            <div ref={stageRef} className="lcars-stage">
              <div className="lcars-stage-bg" />
              <img
                key={current}
                src={current}
                alt={`Design ${idx + 1}`}
                className={"lcars-img select-none cursor-zoom-in " + (dir === 1 ? "slide-in-right" : "slide-in-left")}
                loading="lazy"
                draggable={false}
                onClick={() => setLightbox(idx)}
              />
              <div className="lcars-stage-hud">
                <span className="lcars-dot" />
                <span className="lcars-hud-text">CLICK IMAGE TO OPEN FULLSCREEN</span>
              </div>
            </div>
          </div>

          <div className="lcars-bottom">
            <div className="flex items-center justify-between gap-3">
              <div className="lcars-bottom-label">ALL THUMBNAILS</div>
              <div className="lcars-bottom-meta">Home and End jump. Press R for random.</div>
            </div>

            <div className="lcars-grid" style={{ WebkitOverflowScrolling: "touch" }}>
              {DESIGN_PHOTOS.map((src, i) => (
                <button
                  key={src}
                  className={"lcars-thumb " + (i === idx ? "active" : "")}
                  onClick={() => {
                    setDir(i > idx ? 1 : -1);
                    setIdx(i);
                  }}
                  aria-label={`Go to ${i + 1}`}
                  title={`#${i + 1}`}
                >
                  <img src={src} alt={`Thumb ${i + 1}`} className="w-full h-full object-cover" loading="lazy" draggable={false} />
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-3 text-[11px] text-zinc-500">Tip: arrows to navigate, swipe on the main image, click any thumbnail.</div>
      </div>

      <DesignLightbox photos={DESIGN_PHOTOS} index={lightbox} onClose={() => setLightbox(null)} />
    </div>
  );
}
